### ISSUE TITLE
Theme applied automatically after first install or update

### ISSUE THREAD

**Issue by swapii** [thematic-dev/monokai-pro#7]
Hi!

The theme plugin has just been updated from version 0.2 to 0.3. The updated plugin applied its theme automatically and reset my current other theme.

I think this is an unexpected behaviour for user and should be fixed.

**Comment by jontaydev** [comment]
Sorry about this, thanks for letting me know.

I looked through the JSON and can't seem to figure out why this is happening. If anybody has an idea what is causing this, I would greatly appreciate the help. I don't want to push another update until this gets resolved.

**Comment by jontaydev** [comment]
I submitted an update with fixes last night, so this may occur again. As far as I know, this may be a JetBrains issue since I don't control what gets applied after an update.
