### ISSUE TITLE
Search Window in PYcharm.

### ISSUE THREAD

**Issue by karserasl** [thematic-dev/monokai-pro#8]
Hello

The search window popup (or any other popup) doesnt have a border or shadow, make it indistinguishable from the background

**Comment by jontaydev** [comment]
Could you post a screenshot of what you are seeing? I was able to distinguish the edges on my system (macOS).

**Comment by karserasl** [comment]
Hello, 
Sry for late response.
Here is a screenshot with latest version (0.6).
This is the search window in pycharm. I applied the theme under Appearance. 
A workaround im using , is to use Monokai from Material Theme under Appearance and set the Monokai Pro under Editor Theme.

![image](https://user-images.githubusercontent.com/14327196/86121055-06ee2d80-bade-11ea-989d-36253f4e11f2.png)

**Comment by jontaydev** [comment]
Thanks for pointing this out, I didn't see this originally because Mac shows a border by default. I added a dark border to all popup windows.  The update is submitted to JetBrains (along with a few other fixes), so let me know if this looks better when you get it.
